version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5637:80"
    depends_on:
      - dataBase
  dataBase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "7365:1433"
    environment:
       SA_PASSWORD: "PabloYSamuComenPitoJuntos-6"
       ACCEPT_EULA: "Y"