// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NyxellntAPI.Entities;

#nullable disable

namespace NyxellntAPI.Migrations
{
    [DbContext(typeof(NyxellntDb))]
    [Migration("20230208193818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventoEntity", b =>
                {
                    b.Property<int>("idEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEvento"));

                    b.Property<string>("cantante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precioEntrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("idEvento");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("OperacionEntity", b =>
                {
                    b.Property<int>("idOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOperacion"));

                    b.Property<int?>("UsuarioEntityidUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("eventoCompradoidEvento")
                        .HasColumnType("int");

                    b.Property<string>("fechaCompra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numEntradasCompradas")
                        .HasColumnType("int");

                    b.Property<decimal>("precioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idOperacion");

                    b.HasIndex("UsuarioEntityidUsuario");

                    b.HasIndex("eventoCompradoidEvento");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("UsuarioEntity", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OperacionEntity", b =>
                {
                    b.HasOne("UsuarioEntity", null)
                        .WithMany("eventosComprados")
                        .HasForeignKey("UsuarioEntityidUsuario");

                    b.HasOne("EventoEntity", "eventoComprado")
                        .WithMany()
                        .HasForeignKey("eventoCompradoidEvento");

                    b.Navigation("eventoComprado");
                });

            modelBuilder.Entity("UsuarioEntity", b =>
                {
                    b.Navigation("eventosComprados");
                });
#pragma warning restore 612, 618
        }
    }
}
